### ISSUE TITLE
ObjectManager isn't initialized

### ISSUE THREAD

**Issue by jorgb90** [MagestyApps/module-web-images#11]
> ObjectManager isn't initialized
> #0 /vendor/magento/framework/File/Mime.php(84): Magento\Framework\App\ObjectManager::getInstance()
> #1 /pub/get.php(61): Magento\Framework\File\Mime->__construct()

When uploaded a SVG file and requested at the front-end we are receiving above PHP error.  Any idea?

**Comment by jorgb90** [comment]
@MagestyApps Any idea?

**Comment by jorgb90** [comment]
Seemed to be a strange permissions error..
